name: familio
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  dio: ^5.8.0+1
  intl: ^0.20.2
  auto_route: ^10.1.0+1
  injectable: ^2.5.0
  retrofit: ^4.5.0
  json_annotation: ^4.9.0
  talker: ^4.9.1
  talker_flutter: ^4.9.1
  talker_logger: ^4.9.1
  talker_dio_logger: ^4.9.1
  talker_bloc_logger: ^4.9.1
  path_provider: ^2.1.5
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.1
  firebase_analytics: ^11.5.1
  freezed_annotation: ^3.0.0
  intl_utils: ^2.8.11
  collection: ^1.19.1
  url_launcher: ^6.3.1
  flutter_svg: ^2.2.0
  permission_handler: ^12.0.0+1
  image_picker: ^1.1.2
  path: ^1.9.1
  shared_preferences: ^2.5.3
  in_app_purchase: ^3.2.3
  package_info_plus: ^8.3.0
  uuid: ^4.5.1
  feedback: ^3.1.0
  firebase_crashlytics: ^4.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  auto_route_generator: ^10.1.0
  injectable_generator: ^2.7.0
  retrofit_generator: ^9.2.0
  json_serializable: ^6.9.5
  freezed: ^3.0.6
  flutter_launcher_icons: ^0.14.4
  flutter_gen_runner: ^5.10.0

flutter:
  uses-material-design: true

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter_intl:
  enabled: true
  arb_dir: assets/i18n

flutter_gen:
  integrations:
    flutter_svg: true
  output: lib/generated
