// GENERATED CODE EDIT WITH CAUTION
// THIS FILE **WILL NOT** BE REGENERATED
// This file should be version controlled and can be manually edited.
part of 'schema.g.dart';

// While migrations are intelligently created, the difference between some commands, such as
// DropTable vs. RenameTable, cannot be determined. For this reason, please review migrations after
// they are created to ensure the correct inference was made.

// The migration version must **always** mirror the file name

const List<MigrationCommand> _migration_1_up = [
  InsertTable('TaskAssignee'),
  InsertTable('Event'),
  InsertTable('Relationship'),
  InsertTable('Home'),
  InsertTable('EventAttendee'),
  InsertTable('User'),
  InsertTable('Calendar'),
  InsertTable('Task'),
  InsertTable('HomeMember'),
  InsertTable('Invitation'),
  InsertTable('SubTask'),
  InsertColumn('id', Column.varchar, onTable: 'TaskAssignee', unique: true),
  InsertForeignKey(
    'TaskAssignee',
    'Task',
    foreignKeyColumn: 'task_Task_brick_id',
    onDeleteCascade: false,
    onDeleteSetDefault: false,
  ),
  InsertForeignKey(
    'TaskAssignee',
    'User',
    foreignKeyColumn: 'user_User_brick_id',
    onDeleteCascade: false,
    onDeleteSetDefault: false,
  ),
  InsertColumn('assigned_at', Column.datetime, onTable: 'TaskAssignee'),
  InsertColumn('id', Column.varchar, onTable: 'Event', unique: true),
  InsertForeignKey(
    'Event',
    'Calendar',
    foreignKeyColumn: 'calendar_Calendar_brick_id',
    onDeleteCascade: false,
    onDeleteSetDefault: false,
  ),
  InsertColumn('title', Column.varchar, onTable: 'Event'),
  InsertColumn('description', Column.varchar, onTable: 'Event'),
  InsertColumn('start_date', Column.datetime, onTable: 'Event'),
  InsertColumn('end_date', Column.datetime, onTable: 'Event'),
  InsertColumn('is_all_day', Column.boolean, onTable: 'Event'),
  InsertColumn('source', Column.integer, onTable: 'Event'),
  InsertColumn('external_event_id', Column.varchar, onTable: 'Event'),
  InsertColumn('can_edit', Column.boolean, onTable: 'Event'),
  InsertColumn('created_at', Column.datetime, onTable: 'Event'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Event'),
  InsertColumn('id', Column.varchar, onTable: 'Relationship', unique: true),
  InsertForeignKey(
    'Relationship',
    'User',
    foreignKeyColumn: 'user1_User_brick_id',
    onDeleteCascade: false,
    onDeleteSetDefault: false,
  ),
  InsertForeignKey(
    'Relationship',
    'User',
    foreignKeyColumn: 'user2_User_brick_id',
    onDeleteCascade: false,
    onDeleteSetDefault: false,
  ),
  InsertColumn('relationship_type', Column.integer, onTable: 'Relationship'),
  InsertForeignKey(
    'Relationship',
    'Home',
    foreignKeyColumn: 'home_Home_brick_id',
    onDeleteCascade: false,
    onDeleteSetDefault: false,
  ),
  InsertColumn('created_at', Column.datetime, onTable: 'Relationship'),
  InsertColumn('id', Column.varchar, onTable: 'Home', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'Home'),
  InsertColumn('description', Column.varchar, onTable: 'Home'),
  InsertForeignKey(
    'Home',
    'User',
    foreignKeyColumn: 'owner_User_brick_id',
    onDeleteCascade: false,
    onDeleteSetDefault: false,
  ),
  InsertColumn('allow_member_invite', Column.boolean, onTable: 'Home'),
  InsertColumn('created_at', Column.datetime, onTable: 'Home'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Home'),
  InsertColumn('id', Column.varchar, onTable: 'EventAttendee', unique: true),
  InsertForeignKey(
    'EventAttendee',
    'Event',
    foreignKeyColumn: 'event_Event_brick_id',
    onDeleteCascade: false,
    onDeleteSetDefault: false,
  ),
  InsertForeignKey(
    'EventAttendee',
    'User',
    foreignKeyColumn: 'user_User_brick_id',
    onDeleteCascade: false,
    onDeleteSetDefault: false,
  ),
  InsertColumn('created_at', Column.datetime, onTable: 'EventAttendee'),
  InsertColumn('id', Column.varchar, onTable: 'User', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'User'),
  InsertColumn('avatar', Column.varchar, onTable: 'User'),
  InsertColumn('birth_date', Column.datetime, onTable: 'User'),
  InsertColumn('created_at', Column.datetime, onTable: 'User'),
  InsertColumn('updated_at', Column.datetime, onTable: 'User'),
  InsertColumn('id', Column.varchar, onTable: 'Calendar', unique: true),
  InsertForeignKey(
    'Calendar',
    'User',
    foreignKeyColumn: 'user_User_brick_id',
    onDeleteCascade: false,
    onDeleteSetDefault: false,
  ),
  InsertColumn('name', Column.varchar, onTable: 'Calendar'),
  InsertColumn('is_visible_in_home', Column.boolean, onTable: 'Calendar'),
  InsertColumn('color', Column.varchar, onTable: 'Calendar'),
  InsertColumn('calendar_type', Column.integer, onTable: 'Calendar'),
  InsertColumn('external_id', Column.varchar, onTable: 'Calendar'),
  InsertColumn('access_token', Column.varchar, onTable: 'Calendar'),
  InsertColumn('refresh_token', Column.varchar, onTable: 'Calendar'),
  InsertColumn('last_sync_at', Column.datetime, onTable: 'Calendar'),
  InsertColumn('sync_enabled', Column.boolean, onTable: 'Calendar'),
  InsertForeignKey(
    'Calendar',
    'Home',
    foreignKeyColumn: 'home_Home_brick_id',
    onDeleteCascade: false,
    onDeleteSetDefault: false,
  ),
  InsertColumn('created_at', Column.datetime, onTable: 'Calendar'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Calendar'),
  InsertColumn('id', Column.varchar, onTable: 'Task', unique: true),
  InsertForeignKey(
    'Task',
    'Home',
    foreignKeyColumn: 'home_Home_brick_id',
    onDeleteCascade: false,
    onDeleteSetDefault: false,
  ),
  InsertColumn('title', Column.varchar, onTable: 'Task'),
  InsertColumn('description', Column.varchar, onTable: 'Task'),
  InsertForeignKey(
    'Task',
    'User',
    foreignKeyColumn: 'created_by_User_brick_id',
    onDeleteCascade: false,
    onDeleteSetDefault: false,
  ),
  InsertColumn('status', Column.integer, onTable: 'Task'),
  InsertColumn('due_date', Column.datetime, onTable: 'Task'),
  InsertColumn('priority', Column.integer, onTable: 'Task'),
  InsertColumn('start_date', Column.datetime, onTable: 'Task'),
  InsertColumn('estimated_duration_minutes', Column.integer, onTable: 'Task'),
  InsertColumn('location', Column.varchar, onTable: 'Task'),
  InsertColumn('tags', Column.varchar, onTable: 'Task'),
  InsertColumn('created_at', Column.datetime, onTable: 'Task'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Task'),
  InsertColumn('id', Column.varchar, onTable: 'HomeMember', unique: true),
  InsertForeignKey(
    'HomeMember',
    'Home',
    foreignKeyColumn: 'home_Home_brick_id',
    onDeleteCascade: false,
    onDeleteSetDefault: false,
  ),
  InsertForeignKey(
    'HomeMember',
    'User',
    foreignKeyColumn: 'user_User_brick_id',
    onDeleteCascade: false,
    onDeleteSetDefault: false,
  ),
  InsertColumn('can_create_tasks', Column.boolean, onTable: 'HomeMember'),
  InsertColumn('can_edit_tasks', Column.boolean, onTable: 'HomeMember'),
  InsertColumn('can_delete_tasks', Column.boolean, onTable: 'HomeMember'),
  InsertColumn('can_invite_members', Column.boolean, onTable: 'HomeMember'),
  InsertColumn('can_view_all_calendars', Column.boolean, onTable: 'HomeMember'),
  InsertColumn('is_admin', Column.boolean, onTable: 'HomeMember'),
  InsertColumn('joined_at', Column.datetime, onTable: 'HomeMember'),
  InsertColumn('id', Column.varchar, onTable: 'Invitation', unique: true),
  InsertForeignKey(
    'Invitation',
    'Home',
    foreignKeyColumn: 'home_Home_brick_id',
    onDeleteCascade: false,
    onDeleteSetDefault: false,
  ),
  InsertForeignKey(
    'Invitation',
    'User',
    foreignKeyColumn: 'invited_by_User_brick_id',
    onDeleteCascade: false,
    onDeleteSetDefault: false,
  ),
  InsertColumn('invited_email', Column.varchar, onTable: 'Invitation'),
  InsertColumn('invited_user_name', Column.varchar, onTable: 'Invitation'),
  InsertColumn('invitation_code', Column.varchar, onTable: 'Invitation'),
  InsertColumn('status', Column.integer, onTable: 'Invitation'),
  InsertColumn('created_at', Column.datetime, onTable: 'Invitation'),
  InsertColumn('expires_at', Column.datetime, onTable: 'Invitation'),
  InsertColumn('accepted_at', Column.datetime, onTable: 'Invitation'),
  InsertForeignKey(
    'Invitation',
    'User',
    foreignKeyColumn: 'accepted_by_User_brick_id',
    onDeleteCascade: false,
    onDeleteSetDefault: false,
  ),
  InsertColumn('id', Column.varchar, onTable: 'SubTask', unique: true),
  InsertForeignKey(
    'SubTask',
    'Task',
    foreignKeyColumn: 'task_Task_brick_id',
    onDeleteCascade: false,
    onDeleteSetDefault: false,
  ),
  InsertColumn('title', Column.varchar, onTable: 'SubTask'),
  InsertColumn('is_completed', Column.boolean, onTable: 'SubTask'),
  InsertColumn('order_index', Column.integer, onTable: 'SubTask'),
  InsertColumn('created_at', Column.datetime, onTable: 'SubTask'),
  InsertColumn('updated_at', Column.datetime, onTable: 'SubTask'),
  CreateIndex(columns: ['id'], onTable: 'TaskAssignee', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Event', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Relationship', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Home', unique: true),
  CreateIndex(columns: ['id'], onTable: 'EventAttendee', unique: true),
  CreateIndex(columns: ['id'], onTable: 'User', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Calendar', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Task', unique: true),
  CreateIndex(columns: ['id'], onTable: 'HomeMember', unique: true),
  CreateIndex(columns: ['id'], onTable: 'Invitation', unique: true),
  CreateIndex(columns: ['id'], onTable: 'SubTask', unique: true),
];

const List<MigrationCommand> _migration_1_down = [
  DropTable('TaskAssignee'),
  DropTable('Event'),
  DropTable('Relationship'),
  DropTable('Home'),
  DropTable('EventAttendee'),
  DropTable('User'),
  DropTable('Calendar'),
  DropTable('Task'),
  DropTable('HomeMember'),
  DropTable('Invitation'),
  DropTable('SubTask'),
  DropColumn('id', onTable: 'TaskAssignee'),
  DropColumn('task_Task_brick_id', onTable: 'TaskAssignee'),
  DropColumn('user_User_brick_id', onTable: 'TaskAssignee'),
  DropColumn('assigned_at', onTable: 'TaskAssignee'),
  DropColumn('id', onTable: 'Event'),
  DropColumn('calendar_Calendar_brick_id', onTable: 'Event'),
  DropColumn('title', onTable: 'Event'),
  DropColumn('description', onTable: 'Event'),
  DropColumn('start_date', onTable: 'Event'),
  DropColumn('end_date', onTable: 'Event'),
  DropColumn('is_all_day', onTable: 'Event'),
  DropColumn('source', onTable: 'Event'),
  DropColumn('external_event_id', onTable: 'Event'),
  DropColumn('can_edit', onTable: 'Event'),
  DropColumn('created_at', onTable: 'Event'),
  DropColumn('updated_at', onTable: 'Event'),
  DropColumn('id', onTable: 'Relationship'),
  DropColumn('user1_User_brick_id', onTable: 'Relationship'),
  DropColumn('user2_User_brick_id', onTable: 'Relationship'),
  DropColumn('relationship_type', onTable: 'Relationship'),
  DropColumn('home_Home_brick_id', onTable: 'Relationship'),
  DropColumn('created_at', onTable: 'Relationship'),
  DropColumn('id', onTable: 'Home'),
  DropColumn('name', onTable: 'Home'),
  DropColumn('description', onTable: 'Home'),
  DropColumn('owner_User_brick_id', onTable: 'Home'),
  DropColumn('allow_member_invite', onTable: 'Home'),
  DropColumn('created_at', onTable: 'Home'),
  DropColumn('updated_at', onTable: 'Home'),
  DropColumn('id', onTable: 'EventAttendee'),
  DropColumn('event_Event_brick_id', onTable: 'EventAttendee'),
  DropColumn('user_User_brick_id', onTable: 'EventAttendee'),
  DropColumn('created_at', onTable: 'EventAttendee'),
  DropColumn('id', onTable: 'User'),
  DropColumn('name', onTable: 'User'),
  DropColumn('avatar', onTable: 'User'),
  DropColumn('birth_date', onTable: 'User'),
  DropColumn('created_at', onTable: 'User'),
  DropColumn('updated_at', onTable: 'User'),
  DropColumn('id', onTable: 'Calendar'),
  DropColumn('user_User_brick_id', onTable: 'Calendar'),
  DropColumn('name', onTable: 'Calendar'),
  DropColumn('is_visible_in_home', onTable: 'Calendar'),
  DropColumn('color', onTable: 'Calendar'),
  DropColumn('calendar_type', onTable: 'Calendar'),
  DropColumn('external_id', onTable: 'Calendar'),
  DropColumn('access_token', onTable: 'Calendar'),
  DropColumn('refresh_token', onTable: 'Calendar'),
  DropColumn('last_sync_at', onTable: 'Calendar'),
  DropColumn('sync_enabled', onTable: 'Calendar'),
  DropColumn('home_Home_brick_id', onTable: 'Calendar'),
  DropColumn('created_at', onTable: 'Calendar'),
  DropColumn('updated_at', onTable: 'Calendar'),
  DropColumn('id', onTable: 'Task'),
  DropColumn('home_Home_brick_id', onTable: 'Task'),
  DropColumn('title', onTable: 'Task'),
  DropColumn('description', onTable: 'Task'),
  DropColumn('created_by_User_brick_id', onTable: 'Task'),
  DropColumn('status', onTable: 'Task'),
  DropColumn('due_date', onTable: 'Task'),
  DropColumn('priority', onTable: 'Task'),
  DropColumn('start_date', onTable: 'Task'),
  DropColumn('estimated_duration_minutes', onTable: 'Task'),
  DropColumn('location', onTable: 'Task'),
  DropColumn('tags', onTable: 'Task'),
  DropColumn('created_at', onTable: 'Task'),
  DropColumn('updated_at', onTable: 'Task'),
  DropColumn('id', onTable: 'HomeMember'),
  DropColumn('home_Home_brick_id', onTable: 'HomeMember'),
  DropColumn('user_User_brick_id', onTable: 'HomeMember'),
  DropColumn('can_create_tasks', onTable: 'HomeMember'),
  DropColumn('can_edit_tasks', onTable: 'HomeMember'),
  DropColumn('can_delete_tasks', onTable: 'HomeMember'),
  DropColumn('can_invite_members', onTable: 'HomeMember'),
  DropColumn('can_view_all_calendars', onTable: 'HomeMember'),
  DropColumn('is_admin', onTable: 'HomeMember'),
  DropColumn('joined_at', onTable: 'HomeMember'),
  DropColumn('id', onTable: 'Invitation'),
  DropColumn('home_Home_brick_id', onTable: 'Invitation'),
  DropColumn('invited_by_User_brick_id', onTable: 'Invitation'),
  DropColumn('invited_email', onTable: 'Invitation'),
  DropColumn('invited_user_name', onTable: 'Invitation'),
  DropColumn('invitation_code', onTable: 'Invitation'),
  DropColumn('status', onTable: 'Invitation'),
  DropColumn('created_at', onTable: 'Invitation'),
  DropColumn('expires_at', onTable: 'Invitation'),
  DropColumn('accepted_at', onTable: 'Invitation'),
  DropColumn('accepted_by_User_brick_id', onTable: 'Invitation'),
  DropColumn('id', onTable: 'SubTask'),
  DropColumn('task_Task_brick_id', onTable: 'SubTask'),
  DropColumn('title', onTable: 'SubTask'),
  DropColumn('is_completed', onTable: 'SubTask'),
  DropColumn('order_index', onTable: 'SubTask'),
  DropColumn('created_at', onTable: 'SubTask'),
  DropColumn('updated_at', onTable: 'SubTask'),
  DropIndex('index_TaskAssignee_on_id'),
  DropIndex('index_Event_on_id'),
  DropIndex('index_Relationship_on_id'),
  DropIndex('index_Home_on_id'),
  DropIndex('index_EventAttendee_on_id'),
  DropIndex('index_User_on_id'),
  DropIndex('index_Calendar_on_id'),
  DropIndex('index_Task_on_id'),
  DropIndex('index_HomeMember_on_id'),
  DropIndex('index_Invitation_on_id'),
  DropIndex('index_SubTask_on_id'),
];

//
// DO NOT EDIT BELOW THIS LINE
//

@Migratable(version: '1', up: _migration_1_up, down: _migration_1_down)
class Migration1 extends Migration {
  const Migration1()
    : super(version: 1, up: _migration_1_up, down: _migration_1_down);
}
