// GENERATED CODE DO NOT EDIT
// This file should be version controlled
import 'package:brick_sqlite/db.dart';
part '1.migration.dart';

/// All intelligently-generated migrations from all `@Migratable` classes on disk
final migrations = <Migration>{const Migration1()};

/// A consumable database structure including the latest generated migration.
final schema = Schema(
  1,
  generatorVersion: 1,
  tables: <SchemaTable>{
    SchemaTable(
      'TaskAssignee',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn(
          'task_Task_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Task',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn(
          'user_User_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'User',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('assigned_at', Column.datetime),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'Event',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn(
          'calendar_Calendar_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Calendar',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('title', Column.varchar),
        SchemaColumn('description', Column.varchar),
        SchemaColumn('start_date', Column.datetime),
        SchemaColumn('end_date', Column.datetime),
        SchemaColumn('is_all_day', Column.boolean),
        SchemaColumn('source', Column.integer),
        SchemaColumn('external_event_id', Column.varchar),
        SchemaColumn('can_edit', Column.boolean),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'Relationship',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn(
          'user1_User_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'User',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn(
          'user2_User_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'User',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('relationship_type', Column.integer),
        SchemaColumn(
          'home_Home_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Home',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('created_at', Column.datetime),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'Home',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('name', Column.varchar),
        SchemaColumn('description', Column.varchar),
        SchemaColumn(
          'owner_User_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'User',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('allow_member_invite', Column.boolean),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'EventAttendee',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn(
          'event_Event_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Event',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn(
          'user_User_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'User',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('created_at', Column.datetime),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'User',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('name', Column.varchar),
        SchemaColumn('avatar', Column.varchar),
        SchemaColumn('birth_date', Column.datetime),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'Calendar',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn(
          'user_User_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'User',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('name', Column.varchar),
        SchemaColumn('is_visible_in_home', Column.boolean),
        SchemaColumn('color', Column.varchar),
        SchemaColumn('calendar_type', Column.integer),
        SchemaColumn('external_id', Column.varchar),
        SchemaColumn('access_token', Column.varchar),
        SchemaColumn('refresh_token', Column.varchar),
        SchemaColumn('last_sync_at', Column.datetime),
        SchemaColumn('sync_enabled', Column.boolean),
        SchemaColumn(
          'home_Home_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Home',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'Task',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn(
          'home_Home_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Home',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('title', Column.varchar),
        SchemaColumn('description', Column.varchar),
        SchemaColumn(
          'created_by_User_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'User',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('status', Column.integer),
        SchemaColumn('due_date', Column.datetime),
        SchemaColumn('priority', Column.integer),
        SchemaColumn('start_date', Column.datetime),
        SchemaColumn('estimated_duration_minutes', Column.integer),
        SchemaColumn('location', Column.varchar),
        SchemaColumn('tags', Column.varchar),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'HomeMember',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn(
          'home_Home_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Home',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn(
          'user_User_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'User',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('can_create_tasks', Column.boolean),
        SchemaColumn('can_edit_tasks', Column.boolean),
        SchemaColumn('can_delete_tasks', Column.boolean),
        SchemaColumn('can_invite_members', Column.boolean),
        SchemaColumn('can_view_all_calendars', Column.boolean),
        SchemaColumn('is_admin', Column.boolean),
        SchemaColumn('joined_at', Column.datetime),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'Invitation',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn(
          'home_Home_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Home',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn(
          'invited_by_User_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'User',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('invited_email', Column.varchar),
        SchemaColumn('invited_user_name', Column.varchar),
        SchemaColumn('invitation_code', Column.varchar),
        SchemaColumn('status', Column.integer),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('expires_at', Column.datetime),
        SchemaColumn('accepted_at', Column.datetime),
        SchemaColumn(
          'accepted_by_User_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'User',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
    SchemaTable(
      'SubTask',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn(
          'task_Task_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Task',
          onDeleteCascade: false,
          onDeleteSetDefault: false,
        ),
        SchemaColumn('title', Column.varchar),
        SchemaColumn('is_completed', Column.boolean),
        SchemaColumn('order_index', Column.integer),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
      },
      indices: <SchemaIndex>{
        SchemaIndex(columns: ['id'], unique: true),
      },
    ),
  },
);
