import 'package:auto_route/auto_route.dart';
import 'package:injectable/injectable.dart';

// This file will be generated by build_runner
import 'app_router.gr.dart';

/// Main router configuration for the application
@singleton
@AutoRouterConfig()
class AppRouter extends RootStackRouter {
  @override
  List<AutoRoute> get routes => [
    // Splash route - initial route
    AutoRoute(page: SplashRoute.page, initial: true, path: '/'),

    // Auth route - public access
    AutoRoute(page: AuthRoute.page, path: '/auth'),

    // Home route - no guard needed, handled by splash page
    AutoRoute(page: HomeRoute.page, path: '/home'),
  ];
}
