import 'package:auto_route/auto_route.dart';
import 'package:injectable/injectable.dart';

// This file will be generated by build_runner
import 'app_router.gr.dart';

/// Main router configuration for the application
@singleton
@AutoRouterConfig()
class AppRouter extends RootStackRouter {
  @override
  List<AutoRoute> get routes => [
    AutoRoute(page: SplashRoute.page, initial: true, path: '/splash'),
    AutoRoute(page: AuthRoute.page, path: '/auth'),
    AutoRoute(
      page: MainRoute.page,
      path: '/',
      children: [
        AutoRoute(page: HomeRoute.page, path: 'home'),
        AutoRoute(page: TasksRoute.page, path: 'tasks'),
        AutoRoute(page: CalendarRoute.page, path: 'calendar'),
        AutoRoute(page: ProfileRoute.page, path: 'profile'),
      ],
    ),
  ];
}
