// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXeJrI7gyMQfsTqEfsR1YyH0rvhoP3-Lo',
    appId: '1:646437987857:android:a1873593038aba9168b3b0',
    messagingSenderId: '646437987857',
    projectId: 'familio-project',
    storageBucket: 'familio-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGnHCTptqvTl9xt4MxReE7m3cv1lp8UZg',
    appId: '1:646437987857:ios:a4ca9ab9a557621368b3b0',
    messagingSenderId: '646437987857',
    projectId: 'familio-project',
    storageBucket: 'familio-project.firebasestorage.app',
    iosBundleId: 'com.familio.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBktFFNmQDZdud0HmXQFrXzm2Xa8zip314',
    appId: '1:646437987857:web:99d23f954d4ea44768b3b0',
    messagingSenderId: '646437987857',
    projectId: 'familio-project',
    authDomain: 'familio-project.firebaseapp.com',
    storageBucket: 'familio-project.firebasestorage.app',
    measurementId: 'G-2GK6C7JDNX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGnHCTptqvTl9xt4MxReE7m3cv1lp8UZg',
    appId: '1:646437987857:ios:a4ca9ab9a557621368b3b0',
    messagingSenderId: '646437987857',
    projectId: 'familio-project',
    storageBucket: 'familio-project.firebasestorage.app',
    iosBundleId: 'com.familio.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBktFFNmQDZdud0HmXQFrXzm2Xa8zip314',
    appId: '1:646437987857:web:1f964421c70b4a4368b3b0',
    messagingSenderId: '646437987857',
    projectId: 'familio-project',
    authDomain: 'familio-project.firebaseapp.com',
    storageBucket: 'familio-project.firebasestorage.app',
    measurementId: 'G-PXY2QY23SC',
  );
}
